repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.3
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_tflint
    - id: terraform_validate
      args:
        - --hook-config=--retry-once-with-cleanup=true
    - id: terraform_tfsec
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
